org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.20
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=official
mapping_version=1.20.1

mod_id=taczmorearmor
mod_name=TACZ: More Types of Body Armor
mod_license=CC-BY-NC-4.0
mod_version=1.0.0-beta
mod_group_id=com.taczmorearmor
mod_authors=XYxianyu
mod_description=为TACZ添加更多种类的防弹衣。

geckolib_version=4.8.4